### ISSUE TITLE
Extract IMAGE tag as optional argument to docker-build and deploy-operator

### ISSUE THREAD

**Issue by aslakknutsen** [aslakknutsen/istio-workspace#7]

**Comment by bartoszmajsak** [comment]
@aslakknutsen can you add more description in the issue? I'm not sure what is the goal here. Do you want `$(DOCKER_REPO)/$(DOCKER_IMAGE):$(COMMIT)` to be an argument called `IMAGE` with that as default value for `docker-build` target?

Then `deploy-operator` should replace the value of the image in `yaml` descriptors based on that argument? If so should it simple shell text replace or do you want OpenShift template?

**Comment by aslakknutsen** [comment]
> Do you want $(DOCKER_REPO)/$(DOCKER_IMAGE):$(COMMIT) to be an argument called IMAGE with that as default value for docker-build target?

Essentially optionally parameterize DOCKER_IMAGE

> Then deploy-operator should replace the value of the image in yaml descriptors based on that argument? If so should it simple shell text replace or do you want OpenShift template?

Either way is fine, but I guess making it a Template would do.


IMAGE=my-whatever/whatever make docker-build
IMAGE=my-whatever/whatever make deploy-operator

**Comment by bartoszmajsak** [comment]
Thanks, on it.

**Comment by bartoszmajsak** [comment]
> Essentially optionally parameterize DOCKER_IMAGE

Seems to be already there (same with repo):

https://github.com/aslakknutsen/istio-workspace/blob/05d609a3beab15c86d1691f5c487914084becac2/Makefile#L72

so it's only a matter of introducing the templates I think.
